### ISSUE TITLE
Add Stop/Exit/Error worker handler

### ISSUE THREAD

**Issue by pistej** [pixelfederation/swoole-bundle#238]
In our connection pool app we want/need to use this worker events to close connections from pools.

Will create PR and implement workers in same way as  WorkerStartHandler.

**Comment by Rastusik** [comment]
Great! :) Looking forward for the contribution! :)

**Comment by pistej** [comment]
@Rastusik one question about source branch.. to create PR from ... I started from latest released tag  v0.13.1 as from now in develop branch are coroutine changes and sure if it will be out/stable soon ?!

**Comment by Rastusik** [comment]
@pistej please use the `develop` branch as source branch

**Comment by Rastusik** [comment]
seems like coroutine code will be out as experimental feature. it still has some problems and is disabled by default.
