### ISSUE TITLE
Possibility for flexible logging of client requests

### ISSUE THREAD

**Issue by pistej** [pixelfederation/swoole-bundle#251]
I would like to add access logs, in same format/configuration way as apache mod log: http://httpd.apache.org/docs/2.4/mod/mod_log_config.html#examples, whole formatter and mapper is taken from  https://github.com/mezzio/mezzio-swoole

Same as HttpKernelRequestHandler but with extra function to log ...

**Comment by Rastusik** [comment]
closing via #261
